### PR TITLE
Summer Sendoff

### PR DESCRIPTION
**Pull request by Electric108**
News update on what the Ojos Project did this Summer including:

- [ ] Goals we were able to meet
- [ ] Tasks and goals we had to change
- [ ] Features that are still in progess
- [ ]  Plans for the future
- [ ] Forming of the URL

### CODE REVIEW

**Comment by Electric108** [comment]
I think pictures of some of the parts we made and links to different parts of the documentation we make be done.

**Comment by calejvaldez** [comment]
Looking over the news post. A few tips:

- [How to write great alt text in Markdown for accessibility](https://alexwlchan.net/2021/markdown-image-syntax/) (TLDR: Write alt text for screen readers)
- Be mindful of spelling and capitalization (Please enable the [cSpell VS Code extension](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker))
- Consider adding relevant links to specific words. For example, if you're mentioning the [CHI Competition](https://chi2025.acm.org/), link to their homepage as I did here

Overall it looks pretty good. Spelling/capitalization is the only actual caveat before merging.

**Comment by Electric108** [comment]
I was holding off on the CHI competition so we can make an actual blog post on it. And include the link before we link it here.

**Comment by Electric108** [comment]
But I'll add the spelling add it i thought it was already installed

**Comment by calejvaldez** [comment]
In my mind, adding the link regardless of whether the competition is properly introduced or not is more of a user experience issue. People may be curious about the competition and may want to look it up. Instead of making them open a new tab, go to Google, search up CHI Competition, and figure out which is the most updated link... providing the link for them greatly improves the UX because they can just click on the name, imo.

**Pull request merged**
