### PR TITLE
"Symposium Supplemental Content" page

### PR DESCRIPTION
**Pull request by calejvaldez**
## Summary

> [!WARNING]
> DO NOT ADD A QR CODE FOR THIS PATH. It may change.

This page will be used to add supplemental content for our symposium poster. Please add all of your content here.

## Tasks

- [ ] Restructure the page
- [ ] Add a top level image
- [x] Change the path to `/events/2024-symposium/`
- [ ] Maybe add MDX?
  - [ ] Add React animations?
- [ ] Add Iris content
- [ ] Add references
- [ ] Introduce the full team

## `github.dev` Link

[github.dev](https://github.dev/ojosproject/website/blob/symposium-edits/src/pages/events/2024-symposium.md)

## Resources

[Markdown Cheatsheet](https://quickref.me/markdown)

### CODE REVIEW

**Comment by Electric108** [comment]
here is the link for the [qr code](https://qr.io/?gad_source=1&gclid=Cj0KCQjw_-GxBhC1ARIsADGgDjtowbPlvu3cUysQJYhzkM6kHXNxg_9obgB913WdT5Iz6ry9pVdiDYIaAjaWEALw_wcB)

**Comment by calejvaldez** [comment]
> here is the link for the [qr code](https://qr.io/?gad_source=1&gclid=Cj0KCQjw_-GxBhC1ARIsADGgDjtowbPlvu3cUysQJYhzkM6kHXNxg_9obgB913WdT5Iz6ry9pVdiDYIaAjaWEALw_wcB)

The website (seems?) to force us to enable click tracking. We're going to be using [QRCode Monkey](https://www.qrcode-monkey.com/) instead.

**Comment by calejvaldez** [comment]
Here's the code we're going to be placing on the poster:

qr-code symposium

This is for the URL `https://ojosproject.org/events/uci-symposium-2024/`

**Comment by calejvaldez** [comment]
Upcoming changes:

- [ ] Bigger pictures
- [ ] View-only links / embedded links
- [ ] Introduce our team
- [ ] Introduce the project (briefly)
- [ ] Bigger components
- [ ] Change the GIFs
- [ ] Frontpage
- [ ] References to the documents

**Pull request merged**
